### ISSUE TITLE
Demos IoT World/SIDO

### ISSUE THREAD

**Issue by etrousset** [kuzzleio/kuzzle-iot#31]
For the upcoming shows, we want to upgrade the IoT demo with:
- [ ] new visual design of the bord: Bigger Kuzzle logo and simple architecture overview
- [ ] Add a MicroEJ board with simple dashboard UI updating in realtime
- [ ] Remove dependence to Apple Macbook... try to use ethernet adapter on iPhone
- [ ] build 2 more IoT boards + 2 or 3 MicroEJ boards
